Modifications to the schema for validation errors
MobileToolbox/MobileToolboxSchemas pull request #4
Opened 2023-05-15 21:47 UTC by akaat

The data failed to validate in Sage's system. Two types of changes are necessary - one is the format for the `scores` object (which does not require rebuilding the app) and the other is renaming the field that links to the schema. I suggest `schemaIdentifierPath` but if you have other suggestions, please make them and I will change the schema.

2023-05-15 23:10 UTC, syoung-smallwisdom requested changes

2023-05-15 23:10 UTC, syoung-smallwisdom commented on 3DRotation/3DRotationJSONSchema.json
> +    },
@akaat This won't work. You are just introducing a *different* key that is not in the encoding.

2023-05-15 23:10 UTC, syoung-smallwisdom commented on 3DRotation/3DRotationJSONSchema.json
> +    "schemaIdentifierPath" : {
```suggestion
    "$schema" : {
```

2023-05-15 23:10 UTC, syoung-smallwisdom commented on LetterNumberSeries/LetterNumberSeriesJSONSchema.json
> +    "schemaIdentifierPath" : {
```suggestion
    "$schema" : {
```

2023-05-15 23:10 UTC, syoung-smallwisdom commented on ProgressiveMatrices/ProgressiveMatricesJSONSchema.json
> +    "schemaIdentifierPath" : {
```suggestion
    "$schema" : {
```

2023-05-15 23:10 UTC, syoung-smallwisdom commented on VerbalReasoning/VerbalReasoningJSONSchema.json
> +    "schemaIdentifierPath" : {
```suggestion
    "$schema" : {
```

2023-05-15 23:46 UTC, syoung-smallwisdom commented
@akaat Both these changes require rebuilding the app b/c the URL includes the release tag.

2023-05-16 00:46 UTC, akaat commented
Yes, it would require a rebuild. But it's bad practice to use the same name
for 2 different things even if they're in different spots.  We should be
rebuilding it. Or if we're not, it should only be for the pilot as a
band-aid.

On Mon, May 15, 2023, 7:25 PM Shannon Young ***@***.***>
wrote:

> @akaat <https://github.com/akaat> Both these changes require rebuilding
> the app b/c the URL includes the release tag.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MobileToolbox/MobileToolboxSchemas/pull/4#issuecomment-1548761961>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADZJFFP7MOTEFI5QJ7SZQ6LXGLCOHANCNFSM6AAAAAAYCYTMGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-18 15:23 UTC, syoung-smallwisdom approved these changes

2023-05-18 15:37 UTC, merged

2023-05-18 16:28 UTC, philerooski reviewed
Looks good. Will `jsonSchema` be included in the data going forward? I can add it to the Glue table schemas in Bridge Downstream.

2023-05-18 16:33 UTC, akaat commented
It is not included yet, but it is the most likely name for future data. If
you include it now, we will fix on that.

On Thu, May 18, 2023 at 11:29 AM Phil Snyder ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Looks good. Will jsonSchema be included in the data going forward? I can
> add it to the Glue table schemas in Bridge Downstream.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MobileToolbox/MobileToolboxSchemas/pull/4#pullrequestreview-1433037155>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADZJFFID3A7BTZIXB4ZYGOTXGZE43ANCNFSM6AAAAAAYCYTMGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>